### ISSUE TITLE
self hosted

### ISSUE THREAD

**Issue by tristan-k** [the-happy-hippo/sprits-it#12]
Can you provide some install instruction on what to do, if you want to host sprits-it on your private webspace?

**Comment by the-happy-hippo** [comment]
Sure! I'll update the readme shortly. please follow #1... closing as dup of #1

**Comment by the-happy-hippo** [comment]
Hi @tristan-k! I've added instructions in e192484d10e38e52888f308f9b4a4bea21ba5de1 on `develop`. Could you please take a look at https://github.com/the-happy-hippo/sprits-it/blob/e192484d10e38e52888f308f9b4a4bea21ba5de1/README.md and try to see if it works for you? If it seems OK I'll merge it to `master`.
